### ISSUE TITLE
adds custom fields automatically when editing password

### ISSUE THREAD

**Issue by ashgoodman** [marius-wieschollek/passwords#77] opened 2018-09-26 05:12 UTC
If you experience a **BUG** or want to request a **FEATURE** check if there is already a similar issue
 -> https://github.com/marius-wieschollek/passwords/issues?utf8=%E2%9C%93&q=is%3Aissue
 or try the NIGHTLY releases
 -> https://apps.nextcloud.com/apps/passwords/releases

If none of the options above fit you, delete this block and describe your request instead.
Then fill out the form below.
_Remember not to include personal data as this is public._

### System Information
- Nextcloud Version: 13.06
- PHP Version: 7.2
- Passwords Version: 2018.9.1
- Browser and Version: Firefox 62
- Client OS and Version: Ubuntu 18.04
- Server OS and Version: Ubuntu 18.04

### Steps to reproduce
1. Tell us how to reproduce your issue.
Click edit password
change password
click save
Get message requesting you fill in field under custom fields
Open custom fields
see blank custom fields have been auto created
Delete custom fields
save now works
click edit password again for the same password
same process happens again

### Actual result
Click edit password
change password
click save
Get message requesting you fill in field under custom fields
Open custom fields
see custom fields have been auto created
Delete custom fields
save now works
click edit password again for the same password
same process happens again

### Expected result
Custom fields should not be added automatically

**Comment by marius-wieschollek** [comment] 2018-09-27 20:15
I have seen this before, but i can't reproduce it.
Can you reproduce this error with a password?

**Comment by ashgoodman** [comment] 2018-09-28 02:58
@marius-wieschollek 
"Can you reproduce this error with a password?"
Not sure I understand? This is happening with passwords when I try to edit a password

**Comment by marius-wieschollek** [comment] 2018-09-28 13:15
Does this happen with every password or just with some? And does this happen all the time or just sometimes?

**Comment by adanielvv** [comment] 2018-09-28 13:28
Just figured it out:
- edit and save an entry > no problem
- edit and save the same entry > problem
- edit and save the same entry > problem
...
- reload page
- edit and save the same entry > no problem
- edit and save the same entry > problem
...

No need to change the password, or anything else. Just clicking on edit, and then on save.

**Comment by marius-wieschollek** [comment] 2018-09-28 15:06
I think i found and fixed it. You can download the nightly to check if this fixes the bug for you.

**Comment by adanielvv** [comment] 2018-09-28 16:47
Yes, is fixed in [latest nightly](https://git.mdns.eu/nextcloud/passwords/-/jobs/artifacts/testing/download?job=Assemble).

**Comment by marius-wieschollek** [comment] 2018-09-28 17:00
Great. Thanks to you both that you helped to find this issue.

**Closed as completed by marius-wieschollek** 2018-09-28 17:00 UTC
Labels: bug
