### ISSUE TITLE
reorganizing and cleanup passwords GUI

### ISSUE THREAD

**Issue by Tazzios** [marius-wieschollek/passwords#287] opened 2020-08-13 13:15 UTC
**Current Status**
I just imported everything from passman. while reorganizing and cleanup up my passwords was missing some functions.

**1. Show folders (and tags) in the left navigation**
Now i have to drag it al the way up in a list of 150 items to the folder. 
I only can select one item. It would be a lot quicker if you could just drag it on a folder or tags on the left side.
edit: see also #268

**2. Selected multiple / Bulkactions**
Selected multiple items and add them to a folder or tag
To make deleting and rearrange easier.
edit: see also #268

**3. Dont reload after delete or go back to the same place**
Now i have to scroll manually back after every delete 

**4. Update details**
When i click on an item while i have to details open i expect the details adjust accordingly, just like nextcloud core and other apps behave. Now i have to click on the 3 dots and details to update the details. 
(or doesn`t it just work at my nextcloud?)

**5. edit mode but not everything is there to edit?**
When going into edit mode of an item there is no way to also adjust tags or folder.
Which would be quicker for folders then dragging if you got an very long list. 
I know that to see an edit the tags you have to go to details instead, but there is the question why is tags the only editable field? Option to adjust the title would also be nice for example.

Some of my suggestions may contain some overlap to do the same thing.

**Comment by ozls** [comment] 2021-01-14 13:03
Came here to say exactly this. Thank you for bringing this up.

**Comment by marius-wieschollek** [comment] 2021-03-07 12:19
I'm closing this ticket as it has more than one topic. 1, 2 & 3 are already discussed elsewhere. 4 is something i can't reproduce and would be a bug if it still exists. 5 will likely solved in coming releases (after 2021.4.0) once the new edit form is complete.

**Closed as completed by marius-wieschollek** 2021-03-07 12:19 UTC
Labels: feature
