### ISSUE TITLE
"The app was unable to obtain the api access credentials." on no password synchronization

### ISSUE THREAD

**Issue by Quix0r** [marius-wieschollek/passwords#418] opened 2021-08-09 10:17 UTC
### Current behavior:
With no password stored (for the current user and in total) the web page reloads endlessly when you click on "Passwords" (app menu, https://your.instance.invalid/apps/passwords/ ).

### Expected behavior:
When you click "Passwords", a more descriptive message should appear and also no constant reload should happen.

### Steps to reproduce:
1) Install Nextcloud Passwords from NC store
2) Go immediately (after maybe you have to fix some access rights) to "Passwords"
3) You get the message and it reloads endlessly.

This message is a bit confusing (at least to me).

**Comment by marius-wieschollek** [comment] 2021-09-04 10:25
Closing this issue since it's not following the bug report template and I can't reproduce this issue at all. The error message appears if the app was unable to create a session token, not when there are no passwords in the database.

**Closed as completed by marius-wieschollek** 2021-09-04 10:25 UTC
