### ISSUE TITLE
Enable folder sharing.

### ISSUE THREAD

**Issue by Mululu** [marius-wieschollek/passwords#385] opened 2021-05-20 11:56 UTC
**Current Status**
Currently only individual passwords can be shared. If you use the same passwords on business with several people, then it is unnecessary to always share each new password with the group of people.

**Feature Description**
Currently only individual passwords can be shared. If you use the same passwords on business with several people, then it is unnecessary to always share each new password with the group of people.

To solve the problem, it would be great if you could share folders with groups of people. If a password is now created within the folder, the users who see the folder will automatically be shown the new password without having to share it separately

**Additional context**
-

**Comment by Marcquito** [comment] 2021-05-20 21:22
I would also love this! We use this app primarily for work and it's definitely cumbersome to share passwords individually - folders would really take a lot of the cleanup the other person needs to do. Thanks for considering!

**Comment by marius-wieschollek** [comment] 2021-05-21 10:03
Duplicate of #27

**Closed as completed by marius-wieschollek** 2021-05-21 10:03 UTC
Labels: feature, duplicate
