### ISSUE TITLE
Encryption Tests Failed

### ISSUE THREAD

**Issue by mwaeckerlin** [marius-wieschollek/passwords#178] opened 2019-07-21 15:21 UTC
Got a message:
```
Passwords is testing a new encryption.
This test failed with your browser.
Please open a ticket on our issue tracker or send us an email with this data attached:
```

So here is the data, already base64-decrypted:
```json
{"error":{"message":"Unable to complete request","stack":["no stack"]},"userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0","protocol":"https:","crypto":true,"textencoder":true,"app":"2019.7.2","apps":["accessibility","activity","apporder","calendar","carnet","cloud_federation_api","comments","contacts","dav","deck","drawio","federatedfilesharing","federation","files","files_external","files_markdown","files_mindmap","files_pdfviewer","files_rightclick","files_sharing","files_texteditor","files_trashbin","files_versions","files_videoplayer","firstrunwizard","gallery","logreader","lookup_server_connector","music","nextcloud_announcements","notes","notifications","oauth2","ocsms","onlyoffice","password_policy","passwords","phonetrack","polls","privacy","provisioning_api","quicknotes","radio","rainloop","recommendations","serverinfo","sharebymail","spreed","support","survey_client","systemtags","tasks","theming","twofactor_backupcodes","updatenotification","user_ldap","viewer","workflowengine"]}
```

### System Information
- Nextcloud Version: 16.0.3
- PHP Version: 7.2.19-0ubuntu0.18.04.1
- Passwords Version: 2019.7.2
- Browser and Version: Firefox 68.0
- Client OS and Version: Ubuntu 18.04
- Server OS and Version: Ubuntu 18.04 in Docker

**Comment by marius-wieschollek** [comment] 2019-09-16 17:13
It looks like the issue was not caused by the encryption process and instead a request could not finish. I think this issue should be fixed if you run `./occ maintenance:repair` from the cli. 

Thanks for reporting the issue.

**Closed as completed by marius-wieschollek** 2019-09-16 17:13 UTC
Labels: bug
