### ISSUE TITLE
Share Password Folder

### ISSUE THREAD

**Issue by BlunderingBushcraft** [marius-wieschollek/passwords#525] opened 2022-08-24 12:22 UTC
**Current Status**
Describe the current situation and resulting problems.

Currently you can share individual passwords and you can organize passwords into folders. However you can not share a folder of passwords.

**Feature Description**
Describe your feature and how it should work.

There are groups of passwords that I need to share together that I would like to be able to move to a folder and just share the folder.

**Additional context**

It is mainly something I would like to be able to use for onboarding new users at work to give them all there starter passwords and sharing with family members or babysitters  at home  to quickly give access to Netflix etc. Please let me know if more context is needed or if anything is unclear.

**Comment by fuse314** [comment] 2022-08-24 15:05
duplicate of #27

**Closed as completed** 2022-08-24 19:08 UTC
Labels: feature, duplicate
