### ISSUE TITLE
Some data is waiting to be synchronized

### ISSUE THREAD

**Issue by ronik101** [marius-wieschollek/passwords#239] opened 2020-01-29 11:04 UTC
### System Information
- Nextcloud Version: 17.0.1
- PHP Version: 7.2.10
- Passwords Version: 2020.1.0
- Browser and Version: Google Chrome 79.0.3945.130
- Client OS and Version: Windows 10 Pro 10.0.18362 N/A Build 18362
- Server OS and Version: Centos 7 7.6.1810

### Steps to reproduce
1. Nearly 600-800 passwords and 50 users
2. Start actively sharing one password for multiple users one after another.

### Actual result
1. After a few share operations complete, for all future attempts "Some data is waiting to be synchronized" message displayed when hover the mouse on user icon.
2. Password is shared only after 4 hours.

### Expected result
All attempts to share password are succeed within several seconds.

### Nextcloud log
Message "Info | passwords | Passwords runs /index.php/apps/passwords/cron/sharing in global mode" appears every second

### Important
1. When sharing stops working you can see a growing queue in the database with the following query:
"select uuid, user_id, receiver, source_updated, target_updated, editable, shareable, FROM_UNIXTIME(created), FROM_UNIXTIME(updated) from oc_passwords_entity_share where deleted=0 and target_password is null order by created desc;"
2. 4 hours after the first unsuccessful attempt to share a password, all the pending queries are excecuted successfuly. If I understand correctly, this is the reason why: /var/www/nextcloud/apps/passwords/lib/Cron/SynchronizeShares.php
 $this->config->getAppValue(self::EXECUTION_TIMESTAMP, 0) < strtotime('-4 hours');
3. It appers that consequent share queries are conflicting or blocking each other - if the query starts before the previous one is not finished, everything stucks for 4 hours.

**Comment by marius-wieschollek** [comment] 2020-01-29 11:48
This report is incomplete.
Please add the missing "Actual result" and add a more detailed description in "Expected result"

**Comment by ronik101** [comment] 2020-01-29 16:25
Hello, @marius-wieschollek 
I edited and added information

**Comment by ronik101** [comment] 2020-01-31 07:03
Our problem is very similar to this  #225

**Comment by marius-wieschollek** [comment] 2020-02-02 17:57
I was unable to reproduce this issue. The SQL statement you posted does not look like it is created by the app. The app always selects all fields, does not convert the timestamps and also does not apply any sorting.

The `EXECUTION_TIMESTAMP` is there to prevent two jobs being executed at the same time. A successful job would remove the timestamp after it has finished. So i would assume that the job crashed for some reason. In that case there should be an error in the Nextcloud log at the time when the password was shared. Can you check that?

**Comment by ronik101** [comment] 2020-02-03 05:49
We wrote this sql request manually to see the queue.

> The EXECUTION_TIMESTAMP is there to prevent two jobs being executed at the same time. A successful job would remove the timestamp after it has finished. 

Ok, we got it

>  In that case there should be an error in the Nextcloud log at the time when the password was shared. Can you check that?

Logs only message "Passwords runs /index.php/apps/passwords/cron/sharing in global mode"
Our log level is 1

**Comment by ronik101** [comment] 2020-02-05 05:15
@marius-wieschollek, according to our observations, if you start sharing for one user and before waiting for it to complete sharing for the second user, then only the first process will be executed, all subsequent ones will be queued and executed in 4 hours

**Comment by ronik101** [comment] 2020-02-06 07:17
After execution "config:app:delete passwords cron/sharing/time" the queue is running and sharing is successful for all in queue

**Comment by marius-wieschollek** [comment] 2020-05-02 14:38
Is there still an issue with the latest version of the app?

**Comment by GieltjE** [comment] 2020-06-25 11:26
```
{"reqId":"TuZ30tmwbXoi0zEOJVcP","level":1,"time":"2020-06-25T13:09:06+02:00","remoteAddr":"","user":"--","app":"passwords","method":"","url":"--","message":"Passwords runs /var/www/fyn.nl/fyn/cron.php in global mode","userAgent":"--","version":"19.0.0.12"}
{"reqId":"hl8V4RQQJnhPjEg3q0yU","level":1,"time":"2020-06-25T13:14:07+02:00","remoteAddr":"","user":"--","app":"passwords","method":"","url":"--","message":"Passwords runs /var/www/fyn.nl/fyn/cron.php in global mode","userAgent":"--","version":"19.0.0.12"}
{"reqId":"ozDKPWgaHP0F0hZDZ3Pc","level":1,"time":"2020-06-25T13:19:07+02:00","remoteAddr":"","user":"--","app":"passwords","method":"","url":"--","message":"Passwords runs /var/www/fyn.nl/fyn/cron.php in global mode","userAgent":"--","version":"19.0.0.12"}
{"reqId":"cY6U9qyv8jorcH9jMDgS","level":1,"time":"2020-06-25T13:24:07+02:00","remoteAddr":"","user":"--","app":"passwords","method":"","url":"--","message":"Passwords runs /var/www/fyn.nl/fyn/cron.php in global mode","userAgent":"--","version":"19.0.0.12"}
```

**Comment by marius-wieschollek** [comment] 2020-06-26 19:58
@GieltjE From the log you posted i can only see that the app is executing the cron jobs correctly in global mode. Since there has been no feedback from the original author, i will close this ticket.

**Closed as completed by marius-wieschollek** 2020-06-26 19:58 UTC
Labels: bug, waiting for feedback
