### ISSUE TITLE
Passkeys support

### ISSUE THREAD

**Issue by ghost** [marius-wieschollek/passwords#545] opened 2022-11-22 18:12 UTC
**Current Status**
No Passkeys support

**Feature Description**
Passkeys support

FIDO2 is a joint project of the FIDO Alliance and the W3C and enables strong passwordless multifactor authentication.  The procedure is based on the principles of asymmetric encryption and uses second factors such as biometric features, hardware keys, smart cards or TPM modules to log on to a web service.  Some browsers, operating systems and web services are already compatible with FIDO2 and support the process.

The FIDO2 protocol combines the FIDO Alliance's Client to Authenticator Protocol (CTAP) and the W3C's WebAuthn API and can be integrated into browsers, for example.

**Additional context**
https://www.heise.de/news/Passwort-Manager-1Password-ruestet-sich-fuer-passwortlose-Zukunft-7349247.html

https://www.security-insider.de/was-ist-fido2-a-893570/

**Comment by marius-wieschollek** [comment] 2022-11-22 22:36
Please provide a more comprehensive description of your feature e.g.
What is Passkeys?
How would that support look? What action that you can currently not do in the app could you do with the passkeys support?

**Comment by sevmonster** [comment] 2023-02-20 03:53
This is a duplicate of #353. "Passkey" is the public marketing term for the FIDO U2F/FIDO2 protocols and their supporting CTAP/WebAuthn standards. "Passkeys" can be stored on compatible smartphones (Apple supports Touch ID and Face ID integration for example) or with hardware security keys (HSKs) like YubiKeys.

U2F/FIDO2 could be implemented by encrypting/decrypting a master encryption key using the FIDO keypair, replacing (or augmenting) the existing password requirement for CSE/SSE. Adding multiple HSKs to the same account would simply re-encrypt the master key while inside an unlocked vault, so that either HSK can be used for decryption. Multi-key support is not *required*, but without it a user will have to keep that one key on them at all times. I personally have a rotation of 3 YubiKey 5C NFC keys. Multi-key support would also allow a passphrase fallback in case the user loses all their HSKs or cannot access one at some point. If you wanted to be extra secure, a fixed number of uses for passphrases before the encrypted master key for that passphrase is destroyed would fall in line with current industry trends.

The only benefit to implementing U2F/FIDO2 (more specifically just WebAuthn on the client) is the ability to get rid of passwords, and simply rely on HSKs for authentication. I personally already use a cryptographically secure randomly generated password for my vault, and that password is stored on my YubiKeys in an OTP slot. I plug my key in or swipe with NFC to put the password into the client app. My workflow wouldn't change with proper WebAuthn support, but it would make it leagues more secure.

The main hurdle to this that I can see is that it would need to be supported for SSE as well as CSE. That means both PHP and per-app support. I imagine the Android app will not get this feature unless someone steps up to implement it, which would suck since I use it.

Brief history of the specs:
https://www.yubico.com/blog/passkeys-and-the-future-of-modern-authentication/

Technical overview of implementing FIDO2, CTAP2, and WebAuthn:
https://developers.yubico.com/Passkeys/Quick_overview_of_WebAuthn_FIDO2_and_CTAP.html

Like the others in #353, I would also be more than happy to supply HSKs for testing. I recently upgraded from the YubiKey 5 to the 5C, so I have 2 YubiKeys I am not using. They are small enough to be mailed in an envelope.

I also do not know how this factors in to Nextcloud native MFA support or e.g. #187 as I do not use it, my environment uses SAML.

**Comment by aisknab** [comment] 2023-10-15 12:01
I second this, I know it's an older feature request, but i'd love to use a passkey to get into nextcloud passwords after all, i'm logging into nextcloud with a passkey. The webauth can be FIDO2 with pin or something for extra security. Once you do this, the knockon security effect is that keyloggers can't record your master password and get in.

**Comment by marius-wieschollek** [comment] 2023-11-01 15:54
Since this feature request isn't clear, i'm closing it.

**Closed as completed by marius-wieschollek** 2023-11-01 15:54 UTC
Labels: feature

**Comment by aisknab** [comment] 2023-11-01 19:44
Do you not have a yubikey or a nitrokey? 

One form of a passkey is a USB stick that you touch in order to start a cryptographic process to login to anything that supports it. Google are making passkeys mandatory now.

How is it not clear?

On 1 November 2023 3:54:42 pm UTC, "M. Wieschollek" ***@***.***> wrote:
>Since this feature request isn't clear, i'm closing it. 
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/marius-wieschollek/passwords/issues/545#issuecomment-1789207430
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
-- 
Sent from my mobile. Please excuse my brevity.

**Comment by marius-wieschollek** [comment] 2023-11-01 21:02
This feature request is very vague about how passkeys should be implemented into the app. There are many possible options:

- Implement Passkeys as 2FA, e.g. with the "Tow-Factor WebAuthn" app for NC
- Implement Passkeys for encryption/login using WebAuthn -> see #353 
- Implement Passkeys for encryption/login with anything other than WebAuthn
- Be the Passkey e.g. by providing apps & apis that allows you to to use your phone etc. as the passkey but the central data is held by the server?

This ticket is just "Passkeys support" without the actual information what that support should look like. My guess is that you want to log in with the key in which case we already have a ticket for this.

**Comment by aisknab** [comment] 2023-11-01 22:51
Yes, login with the passkey. 

Thankyou for the clarification, you guys are doing an amazing job with this extension and I wanted to thank you for your work on it for the open source community. Very much appreciated.



On 1 November 2023 9:02:21 pm UTC, "M. Wieschollek" ***@***.***> wrote:
>This feature request is very vague about how passkeys should be implemented into the app. There are many possible options:
>
>- Implement Passkeys as 2FA, e.g. with the "Tow-Factor WebAuthn" app for NC
>- Implement Passkeys for encryption/login using WebAuthn -> see #353 
>- Implement Passkeys for encryption/login with anything other than WebAuthn
>- Be the Passkey e.g. by providing apps & apis that allows you to to use your phone etc. as the passkey but the central data is held by the server?
>
>This ticket is just "Passkeys support" without the actual information what that support should look like. My guess is that you want to log in with the key in which case we already have a ticket for this.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/marius-wieschollek/passwords/issues/545#issuecomment-1789680872
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
-- 
Sent from my mobile. Please excuse my brevity.
