### ISSUE TITLE
Passwords generator "Random characters" uses Umlauts etc

### ISSUE THREAD

**Issue by simonspa** [marius-wieschollek/passwords#222] opened 2019-12-31 15:04 UTC
Not entirely sure whether this qualifies as bug or is rather a feature request.

When e.g. having set Nextcloud language to German, the password generator includes diacritics and umlauts in the generated passwords. They are treated as "normal" characters. Imho this behavior is problematic because

 * a) many services don't accept this type of characters in their passwords
 * b) there is no way to exclude the from the generated passwords
 * c) when logging in from a computer with different keyboard layout they might not be available

Would it be possible to make this optional or to at least restrict to the standard character set by default?

### System Information
- Nextcloud Version: 17.0.1
- Passwords Version: 2019.12.1

### Steps to reproduce
1. Switch Nextcloud to German
2. Create new password in the app
3. Click on the "generate" button

### Actual result
A password is generated which contains e.g. "Ä" or "ß"

### Expected result
A password should be generated which is usable without problems on major pages

**Comment by marius-wieschollek** [comment] 2020-05-02 14:58
Is a duplicate of #97 for me

**Closed as completed by marius-wieschollek** 2020-05-02 14:58 UTC
