### ISSUE TITLE
[BUG]: Exception: OCA\Passwords\Notification\UpgradeRequiredNotification::getMessage(): Argument #4 ($appVersion) must be of type string, null given

### ISSUE THREAD

**Issue by roru69** [marius-wieschollek/passwords#628] opened 2024-01-10 09:21 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
{
    "version": {
        "server": "27.1.5.1",
        "app": "2023.12.32",
        "lsr": false,
        "php": "8.2.14",
        "cronPhp": "8.2.14"
    },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "mysql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": true,
        "subdirectory": false
    },
    "services": {
        "images": "imagick",
        "favicons": "bi",
        "previews": "pageres",
        "security": "hibp",
        "words": "auto",
        "previewApi": false,
        "faviconApi": false
    },
    "status": {
        "autoBackupRestored": false
    },
    "settings": {
        "channel": "beta",
        "nightlies": false,
        "handbook": false,
        "performance": 5
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "SSEv3r1": false,
            "none": false,
            "default": "SSEv1r2"
        },
        "cse": {
            "CSEv1r1": false,
            "none": true,
            "default": "none"
        }
    }
}
```

### Client Information

Browser and Version: Edge - Version 120.0.2210.121 (Official build) (64-bits)
Client OS and Version: Windows Server 2019 

Nextcloud is running behind a IIS reverse proxy.

### Bug description

Every 5 seconds the following exception is thrown in the nextcloud log:

Exception: OCA\Passwords\Notification\UpgradeRequiredNotification::getMessage(): Argument #4 ($appVersion) must be of type string, null given, called in /var/www/nextcloud/apps/passwords/lib/Notification/UpgradeRequiredNotification.php on line 89 in file '/var/www/nextcloud/apps/passwords/lib/Notification/UpgradeRequiredNotification.php' line 128

Undefined array key "appVersion" at /var/www/nextcloud/apps/passwords/lib/Notification/UpgradeRequiredNotification.php#89

### Steps to reproduce

Everything seems to work fine, only my log is getting hammered by this exeption

### Expected behavior

No exceptions in the Nextcloud log

### Nextcloud Logs

```shell
Exception: OCA\Passwords\Notification\UpgradeRequiredNotification::getMessage(): Argument #4 ($appVersion) must be of type string, null given, called in /var/www/nextcloud/apps/passwords/lib/Notification/UpgradeRequiredNotification.php on line 89 in file '/var/www/nextcloud/apps/passwords/lib/Notification/UpgradeRequiredNotification.php' line 128

Undefined array key "appVersion" at /var/www/nextcloud/apps/passwords/lib/Notification/UpgradeRequiredNotification.php#89
```

**Comment by nikhub** [comment] 2024-01-22 10:31
I can confirm the exact same issue.
The error message appears at least every minute in my Nextcloud Servers log file.
Nextcloud Server version: 27.1.5.1
Passwords App version: 2023.12.32

```
Exception: OCA\Passwords\Notification\UpgradeRequiredNotification::getMessage(): Argument #4 ($appVersion) must be of type string, null given, called in /var/www/html/nextcloud/apps/passwords/lib/Notification/UpgradeRequiredNotification.php on line 89 in file '/var/www/html/nextcloud/apps/passwords/lib/Notification/UpgradeRequiredNotification.php' line 128
```

**Comment by marius-wieschollek** [comment] 2024-03-09 13:02
Is this issue still present with the current version of the app?

**Comment by nikhub** [comment] 2024-03-09 23:23
I recently updated to Nextcloud 28.0.3 and PHP8.3.
Nextcloud Passwords App version currently is 2024.3.20.
I checked my log for the error message, but could not find it. Looks like it is fixed in my case.
Thank you very much!

**Comment by roru69** [comment] 2024-03-11 07:40
Same here. No more entries in my log concerning this error.  Now on Nextcloud 2.8.0.3 - Latest build Passwords. So it looks fixed in my case also! Thanks!!

**Closed as completed** 2024-03-13 06:56 UTC
Labels: bug
