### ISSUE TITLE
Share Password Folder with Groups

### ISSUE THREAD

**Issue by skumpusch** [marius-wieschollek/passwords#206] opened 2019-11-05 12:52 UTC
**Current Status**
Describe the current situation and resulting problems.
You only can Share a Single Password not a Folder and you can also not Share with a Group.
We need many Passwords we want to share across the Company with the current situation it is very time intensive because we have to share every single password with around 20Users. 

**Feature Description**
Describe your feature and how it should work.
We want to Share a folder with a Group so if you share the hole Folder every User in that Group can create show delete....  every Password in the Folder.

**Additional context**

**Comment by helmo** [comment] 2019-11-13 09:12
This is a duplicate of #27, please comment or upvote there.

**Closed as completed** 2019-12-03 20:18 UTC
Labels: duplicate
