### ISSUE TITLE
Upgrade to Nextcloud 17 beta1 results in white page in Passwords app

### ISSUE THREAD

**Issue by moretocome** [marius-wieschollek/passwords#184] opened 2019-08-19 13:10 UTC
I stupidly trusted the updater telling my all my apps would have updates for Nextcloud 17 beta1 and upgraded my server. Now when I try to access the passwords app, I get a white page in the browser.

I know it is my own mistake, but I just thought I'd give you a heads up. Thanks for the good work!

I tried both 2019.8.0 and 2019.8.1, both results in the same white page.

### System Information
- Nextcloud Version: 17 beta 1
- PHP Version: 7.3
- Passwords Version: 2019.8.1
- Browser and Version: Firefox 68.0.2
- Client OS and Version: Linux Min 19.2
- Server OS and Version: Debian "Buster"

### Steps to reproduce
1. Upgrade Nextcloud server to 17 beta1
2. Go to "Apps" and enable untested Passwords app
3. Try to access passwords app

### Actual result
Browser shows an empty white page.

### Expected result
What should happen?

### Nextcloud log
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"QdvfZ2SOOOS5fw9IxT4e","level":3,"time":"2019-08-19T15:06:22+02:00","remoteAddr":"[client IP]","user":"[client user name]","app":"no app in context","method":"GET","url":"/svg/core/places/contacts?color=000&v=1","message":{"Exception":"InvalidArgumentException","Message":"Notifier Passwords (id: passwords) is not considered because it is using the old way to register.","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/passwords/lib/AppInfo/Application.php","line":218,"function":"registerNotifier","class":"OC\\Notification\\Manager","type":"->","args":[{"__class__":"Closure"},{"__class__":"Closure"}]},{"file":"/var/www/nextcloud/apps/passwords/lib/AppInfo/Application.php","line":69,"function":"registerNotificationNotifier","class":"OCA\\Passwords\\AppInfo\\Application","type":"->","args":[]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":373,"function":"__construct","class":"OCA\\Passwords\\AppInfo\\Application","type":"->","args":[]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":351,"function":"setupRoutes","class":"OC\\Route\\Router","type":"->","args":[{"resources":{"admin_settings":{"url":"/admin/settings"},"admin_caches":{"url":"/admin/caches"},"legacy_category_api":{"url":"/api/0.1/categories"},"legacy_password_api":{"url":"/api/0.1/passwords"},"legacy_version_api":{"url":"/api/0.1/version"}},"routes":[{"name":"page#index","url":"/","verb":"GET"},{"name":"cron#execute","url":"/cron/{job}","verb":"GET"},{"name":"notification#survey","url":"/notification/survey/{answer}","verb":"GET"},{"name":"session_api#request","url":"/api/1.0/session/request","verb":"GET"},{"name":"session_api#open","url":"/api/1.0/session/open","verb":"POST"},{"name":"session_api#close","url":"/api/1.0/session/close","verb":"GET"},{"name":"session_api#keep_alive","url":"/api/1.0/session/keepalive","verb":"GET"},{"name":"session_api#request_token","url":"/api/1.0/token/{provider}/request","verb":"GET"},{"name":"keychain_api#list","url":"/api/1.0/keychain/get","verb":"GET"},{"name":"keychain_api#update","url":"/api/1.0/keychain/set","verb":"POST"},{"name":"account_api#reset","url":"/api/1.0/account/reset","verb":"POST"},{"name":"account_api#get_challenge","url":"/api/1.0/account/challenge/get","verb":"GET"},{"name":"account_api#set_challenge","url":"/api/1.0/account/challenge/set","verb":"POST"},{"name":"password_api#list","url":"/api/1.0/password/list","verb":"GET"},{"name":"password_api#list","url":"/api/1.0/password/list","verb":"POST","postfix":"POST"},{"name":"password_api#show","url":"/api/1.0/password/show","verb":"POST"},{"name":"password_api#find","url":"/api/1.0/password/find","verb":"POST"},{"name":"password_api#create","url":"/api/1.0/password/create","verb":"POST"},{"name":"password_api#update","url":"/api/1.0/password/update","verb":"PATCH"},{"name":"password_api#delete","url":"/api/1.0/password/delete","verb":"DELETE"},{"name":"password_api#restore","url":"/api/1.0/password/restore","verb":"PATCH"},{"name":"folder_api#list","url":"/api/1.0/folder/list","verb":"GET"},{"name":"folder_api#list","url":"/api/1.0/folder/list","verb":"POST","postfix":"POST"},{"name":"folder_api#show","url":"/api/1.0/folder/show","verb":"POST"},{"name":"folder_api#find","url":"/api/1.0/folder/find","verb":"POST"},{"name":"folder_api#create","url":"/api/1.0/folder/create","verb":"POST"},{"name":"folder_api#update","url":"/api/1.0/folder/update","verb":"PATCH"},{"name":"folder_api#delete","url":"/api/1.0/folder/delete","verb":"DELETE"},{"name":"folder_api#restore","url":"/api/1.0/folder/restore","verb":"PATCH"},{"name":"tag_api#list","url":"/api/1.0/tag/list","verb":"GET"},{"name":"tag_api#list","url":"/api/1.0/tag/list","verb":"POST","postfix":"POST"},{"name":"tag_api#show","url":"/api/1.0/tag/show","verb":"POST"},{"name":"tag_api#find","url":"/api/1.0/tag/find","verb":"POST"},{"name":"tag_api#create","url":"/api/1.0/tag/create","verb":"POST"},{"name":"tag_api#update","url":"/api/1.0/tag/update","verb":"PATCH"},{"name":"tag_api#delete","url":"/api/1.0/tag/delete","verb":"DELETE"},{"name":"tag_api#restore","url":"/api/1.0/tag/restore","verb":"PATCH"},{"name":"share_api#list","url":"/api/1.0/share/list","verb":"GET"},{"name":"share_api#list","url":"/api/1.0/share/list","verb":"POST","postfix":"POST"},{"name":"share_api#show","url":"/api/1.0/share/show","verb":"POST"},{"name":"share_api#find","url":"/api/1.0/share/find","verb":"POST"},{"name":"share_api#create","url":"/api/1.0/share/create","verb":"POST"},{"name":"share_api#update","url":"/api/1.0/share/update","verb":"PATCH"},{"name":"share_api#delete","url":"/api/1.0/share/delete","verb":"DELETE"},{"name":"share_api#partners","url":"/api/1.0/share/partners","verb":"GET"},{"name":"share_api#partners","url":"/api/1.0/share/partners","verb":"POST","postfix":"POST"},{"name":"settings_api#get","url":"/api/1.0/settings/get","verb":"POST"},{"name":"settings_api#set","url":"/api/1.0/settings/set","verb":"POST"},{"name":"settings_api#list","url":"/api/1.0/settings/list","verb":"GET"},{"name":"settings_api#list","url":"/api/1.0/settings/list","verb":"POST","postfix":"POST"},{"name":"settings_api#reset","url":"/api/1.0/settings/reset","verb":"POST"},{"name":"service_api#generate_password","url":"/api/1.0/service/password","verb":"GET"},{"name":"service_api#generate_password","url":"/api/1.0/service/password","verb":"POST","postfix":"POST"},{"name":"service_api#get_favicon","url":"/api/1.0/service/favicon/{domain}/{size}","verb":"GET","defaults":{"domain":"default","size":32}},{"name":"service_api#get_avatar","url":"/api/1.0/service/avatar/{user}/{size}","verb":"GET","defaults":{"user":"","size":32}},{"name":"service_api#get_preview","url":"/api/1.0/service/preview/{domain}/{view}/{width}/{height}","verb":"GET","defaults":{"domain":"default","view":"desktop","width":640,"height":"360..."}},{"name":"service_api#coffee","url":"/api/1.0/service/coffee","verb":"GET"},{"name":"tag_api#preflighted_cors","url":"/api/1.0/tag/{path}","verb":"OPTIONS","requirements":{"path":".+"}},{"name":"share_api#preflighted_cors","url":"/api/1.0/share/{path}","verb":"OPTIONS","requirements":{"path":".+"}},{"name":"folder_api#preflighted_cors","url":"/api/1.0/folder/{path}","verb":"OPTIONS","requirements":{"path":".+"}},{"name":"session_api#preflighted_cors","url":"/api/1.0/session/{path}","verb":"OPTIONS","requirements":{"path":".+"}},{"name":"account_api#preflighted_cors","url":"/api/1.0/account/{path}","verb":"OPTIONS","requirements":{"path":".+"}},{"name":"service_api#preflighted_cors","url":"/api/1.0/service/{path}","verb":"OPTIONS","requirements":{"path":".+"}},{"name":"settings_api#preflighted_cors","url":"/api/1.0/setting/{path}","verb":"OPTIONS","requirements":{"path":".+"}},{"name":"keychain_api#preflighted_cors","url":"/api/1.0/keychain/{path}","verb":"OPTIONS","requirements":{"path":".+"}},{"name":"password_api#preflighted_cors","url":"/api/1.0/password/{path}","verb":"OPTIONS","requirements":{"path":".+"}},{"name":"legacy_version_api#preflighted_cors","url":"/api/0.1/version/{path}","verb":"OPTIONS","requirements":{"path":".+"}},{"name":"legacy_category_api#preflighted_cors","url":"/api/1.0/category/{path}","verb":"OPTIONS","requirements":{"path":".+"}},{"name":"legacy_password_api#preflighted_cors","url":"/api/1.0/passwords/{path}","verb":"OPTIONS","requirements":{"path":".+"}}]},"passwords"]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":151,"function":"requireRouteFile","class":"OC\\Route\\Router","type":"->","args":["/var/www/nextcloud/apps/passwords/appinfo/routes.php","passwords"]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":268,"function":"loadRoutes","class":"OC\\Route\\Router","type":"->","args":[]},{"file":"/var/www/nextcloud/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/svg/core/places/contacts"]},{"file":"/var/www/nextcloud/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/lib/private/Notification/Manager.php","Line":86,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0","version":"17.0.0.2","id":"5d5a9ed1c3e31"}
```
and
```
{"reqId":"gHJNBaDVEurwlxzro8Rs","level":3,"time":"2019-08-19T14:57:35+02:00","remoteAddr":"[client IP]","user":"[client user name]","app":"PHP","method":"GET","url":"/apps/passwords/","message":"Declaration of OCA\\Passwords\\Services\\NotificationService::prepare(OCP\\Notification\\INotification $notification, $languageCode) must be compatible with OCP\\Notification\\INotifier::prepare(OCP\\Notification\\INotification $notification, string $languageCode): OCP\\Notification\\INotification at /var/www/nextcloud/apps/passwords/lib/Services/NotificationService.php#28","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0","version":"17.0.0.2","id":"5d5a9ed1c706c"}
```
</details>

### Browser log
<details>
<summary>Browser log</summary>

```
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: https://[server URL]/apps/notifications/js/notifications.js?v=564fba66-4
Source Map URL: notifications.js.map
```
</details>

**Comment by marius-wieschollek** [comment] 2019-08-19 16:15
This is a duplicate of #175.

There is no official version for NC 17 yet. But you can try the nightly from the [app store](https://apps.nextcloud.com/apps/passwords/releases?platform=17#17).

**Closed as completed by marius-wieschollek** 2019-08-19 16:15 UTC
Labels: bug

**Comment by moretocome** [comment] 2019-08-20 06:56
Yes I knew the fault was my own for upgrading, @marius-wieschollek. I just thought I the logs might be useful for something.

But I just upgraded to ```Passwords 2019.9.0-build3120 (nightly) ``` and what do you know: passwords are back and there are no passwords-related errors in my log yet.

Thanks again for a great app! My personal favorite in the NC app store if that means anything to you.
