### ISSUE TITLE
Password sharing deletion bug

### ISSUE THREAD

**Issue by lukas-frey** [marius-wieschollek/passwords#301] opened 2020-10-01 12:47 UTC
### System Information
- Nextcloud Version: 19.0.3
- PHP Version: 7.4
- Database and Version: MySQL5
- Passwords Version: 2020.9.0
- Browser and Version: Firefox 81.0
- Client OS and Version: Windows 10
- Server OS and Version: Ubuntu 20.04

### Steps to reproduce
1. Share Password with someone, give edit rights
2. Delete Password
3. Other member still sees password. Worse is, they can't even delete it now.

### Expected result
Delete passwords on both accounts (ideally), or at least allow to delete it on the shared account.

### Actual result
Breaks totally and can't remove the password anymore.

**Comment by marius-wieschollek** [comment] 2020-10-01 21:20
When you delete a password that is still shared, it should be deleted for all other users as soon as the next cron job runs. This works for me.

But i can reproduce the issue with the other user not being able to delete a password with edit rights if it is deleted by the owner.
This should be fixed with the latest nightly version.

**Closed as completed** 2020-10-04 11:41 UTC
Labels: bug
